# Generated by Django 4.1 on 2022-08-18 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_selection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_selection',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='total_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='vote end date'),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='vote start date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='question',
            name='show_vote',
            field=models.CharField(choices=[('VOTE', 'after vote'), ('END', 'after voting ends'), ('NEVER', 'never')], default='END', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='allow_custom',
            field=models.BooleanField(default=False, verbose_name='allow custom votes'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.TextField()),
                ('storage_loc', models.TextField()),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.TextField()),
                ('file_size', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='vote_count',
        ),
        migrations.AddField(
            model_name='question',
            name='has_max_vote_count',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='show_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('custom_choice_text', models.CharField(blank=True, max_length=200, null=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('DEFAULT', 'default'), ('SUBS', 'subscriber'), ('SA', 'super admin')], default='DEFAULT', max_length=10)),
                ('subs_start', models.DateField(blank=True, null=True, verbose_name='subscription start date')),
                ('subs_expire', models.DateField(blank=True, null=True, verbose_name='subscription expire date')),
                ('followers', models.ManyToManyField(to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.file')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='followers',
            field=models.ManyToManyField(related_name='follows', to='polls.user'),
        ),
        migrations.AddField(
            model_name='question',
            name='thumbmail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.file'),
        ),
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creates', to='polls.user'),
        ),
    ]
