# Generated by Django 4.1 on 2022-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_file_user_vote_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
