# Generated by Django 4.1 on 2022-08-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote_is_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follows', to='polls.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, to='polls.user'),
        ),
    ]
