# Generated by Django 4.1 on 2022-08-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_followers_alter_user_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='thumbmail',
            new_name='thumbnail',
        ),
    ]
