# Generated by Django 4.1 on 2022-08-22 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_thumbmail_question_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.FloatField(default=0)),
                ('enable_email_notify', models.BooleanField(default=False)),
                ('enable_sms_notify', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.FloatField(default=0)),
                ('enable_email_notify', models.BooleanField(default=False)),
                ('enable_sms_notify', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='storage_loc',
            field=models.TextField(verbose_name='storage location'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='followers',
        ),
        migrations.AddField(
            model_name='question',
            name='followers',
            field=models.ManyToManyField(
                blank=True, related_name='follows', through='polls.QuestionFollower', to='polls.user'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(
                blank=True, through='polls.UserFollower', to='polls.user'),
        ),
        migrations.AddField(
            model_name='userfollower',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='polls.user'),
        ),
        migrations.AddField(
            model_name='userfollower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='polls.user'),
        ),
        migrations.AddField(
            model_name='questionfollower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
        migrations.AddField(
            model_name='questionfollower',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
