# Generated by Django 4.1 on 2022-08-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_questionfollower_userfollower_alter_file_storage_loc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionfollower',
            name='enable_sms_notify',
        ),
        migrations.RemoveField(
            model_name='userfollower',
            name='enable_sms_notify',
        ),
        migrations.AddField(
            model_name='questionfollower',
            name='notify_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfollower',
            name='notify_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
