# Generated by Django 4.1 on 2022-08-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_questionfollower_enable_sms_notify_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='followers',
        ),
        migrations.AlterField(
            model_name='question',
            name='followers',
            field=models.ManyToManyField(blank=True, through='polls.QuestionFollower', to='polls.user'),
        ),
        migrations.AlterField(
            model_name='userfollower',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='polls.user'),
        ),
        migrations.AlterField(
            model_name='userfollower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_creates', to='polls.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='question_follows', through='polls.QuestionFollower', to='polls.user'),
        ),
        migrations.AlterField(
            model_name='userfollower',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followed', to='polls.user'),
        ),
        migrations.AlterField(
            model_name='userfollower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follows', to='polls.user'),
        ),
    ]
