# Generated by Django 4.1 on 2022-08-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_question_creator_alter_question_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='followed_users',
        ),
    ]
