# Generated by Django 4.1 on 2022-09-02 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_auth_users(apps, schema_editor):
    polls_user_model = apps.get_model('polls', 'User')
    auth_user_model = apps.get_model('auth', 'User')

    for polls_user in polls_user_model.objects.all():
        name = polls_user.name.replace(' ', '_')
        email = polls_user.email or name.lower() + '@email.com'

        auth_user, _ = auth_user_model.objects.get_or_create(
            username=name, email=email)
        polls_user.account = auth_user

        polls_user.save()
        auth_user.save()


def add_polls_users(apps, schema_editor):
    polls_user_model = apps.get_model('polls', 'User')
    auth_user_model = apps.get_model('auth', 'User')

    for auth_user in auth_user_model.objects.all():
        name = auth_user.username.replace('_', ' ')
        email = auth_user.email or auth_user.username.lower() + '@email.com'

        polls_user, _ = polls_user_model.objects.get_or_create(
            id=auth_user.id)
        polls_user.name = name
        polls_user.email = email

        polls_user.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_rename_followers_user_followed_users'),
    ]
    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_auth_users, add_polls_users),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
