# Generated by Django 4.1 on 2022-09-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_user_email_remove_user_name_user_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['file', 'id']},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['choice_text', 'id']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['file_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_text']},
        ),
        migrations.AlterModelOptions(
            name='questionfollower',
            options={'ordering': ['-ordering', 'question', 'id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['account__username', 'id']},
        ),
        migrations.AlterModelOptions(
            name='userfollower',
            options={'ordering': ['-ordering', 'id']},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-timestamp', 'id']},
        ),
    ]
