# Generated by Django 4.1 on 2022-10-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_choice_deleted_choice_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='deleted_by_cascade',
        ),
    ]
